### ISSUE TITLE
typo in 'advanced usage' suggestion

### ISSUE THREAD

**Issue by daslu** [kxxoling/jupyter-clojure-docker#2]
Hi! Thank you so much for putting this image together!.

In the README, you suggest to bind the local path to /notebooks.
However, in the image, the relevant path to bind is /home/clojure/notebooks.

**Comment by avelino** [comment]
@daslu you send PR?

**Comment by daslu** [comment]
@avelino no problem, I can do it tomorrow if it helps.
Whichever you prefer.

**Comment by daslu** [comment]
https://github.com/kxxoling/jupyter-clojure-docker/pull/3
